apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sxtd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-sxtd@sha256:9168c0fece329e0a7739c9eb062474ae431b451c1f5c617698cbfa072472849c
        name: my-nodejs
        resources: {}
status: {}
